import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_app_check/firebase_app_check.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:hive_flutter/hive_flutter.dart';

import 'app.dart';
import 'firebase_options.dart'; // generated by `flutterfire configure` — see README

Future<void> _firebaseBackgroundHandler(RemoteMessage message) async {
  // Handle background push notifications (new message, call invite, etc.)
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // App Check protects your Firebase backend from abuse/unauthorized clients.
  // Use debug provider for local dev, Play Integrity / DeviceCheck for release.
  await FirebaseAppCheck.instance.activate(
    androidProvider: AndroidProvider.playIntegrity,
    appleProvider: AppleProvider.deviceCheck,
  );

  FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;

  FirebaseMessaging.onBackgroundMessage(_firebaseBackgroundHandler);

  await Hive.initFlutter();
  // TODO: register Hive adapters for MessageModel, ChatModel, etc. once generated
  // via `flutter pub run build_runner build`.

  runApp(const ProviderScope(child: AsharafChatApp()));
}
